package org.apache.commons.lang3.builder;
// Generated by Qodo Gen

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CompareToBuilderQodoTest {


    // Compare primitive types (int, long, float, double, etc) and return correct ordering
    @Test
    public void test_primitive_type_comparison_ordering() {
        CompareToBuilder builder = new CompareToBuilder();

        builder.append(1, 2);
        assertEquals(-1, builder.toComparison());

        builder = new CompareToBuilder();
        builder.append(2, 1); 
        assertEquals(1, builder.toComparison());

        builder = new CompareToBuilder();
        builder.append(1, 1);
        assertEquals(0, builder.toComparison());

        builder = new CompareToBuilder();
        builder.append(1.5f, 2.5f);
        assertEquals(-1, builder.toComparison());

        builder = new CompareToBuilder();
        builder.append(1.5d, 1.5d);
        assertEquals(0, builder.toComparison());
    }

    // Compare arrays of different lengths
    @Test
    public void test_array_length_comparison() {
        CompareToBuilder builder = new CompareToBuilder();

        int[] arr1 = new int[] {1, 2};
        int[] arr2 = new int[] {1, 2, 3};

        builder.append(arr1, arr2);
        assertEquals(-1, builder.toComparison());

        builder = new CompareToBuilder();
        builder.append(arr2, arr1);
        assertEquals(1, builder.toComparison());

        builder = new CompareToBuilder();
        int[] arr3 = new int[] {1, 2};
        builder.append(arr1, arr3);
        assertEquals(0, builder.toComparison());

        builder = new CompareToBuilder();
        builder.append(new int[0], new int[]{1});
        assertEquals(-1, builder.toComparison());
    }
}