
// Generated by Qodo Gen

import org.apache.commons.lang3.builder.HashCodeBuilder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class HashCodeBuilderQodoTest {


    // Basic hash code generation with primitive values using append() methods
    @Test
    public void test_hash_code_with_primitive_values() {
        HashCodeBuilder builder = new HashCodeBuilder(17, 37);
    
        int hashCode = builder
            .append(true)
            .append(123)
            .append(45.67f)
            .append(89.012)
            .append('a')
            .toHashCode();
    
        assertNotEquals(0, hashCode);
        assertEquals(hashCode, builder.toHashCode());
    }

    // Handling null values in append() methods
    @Test
    public void test_hash_code_with_null_values() {
        HashCodeBuilder builder = new HashCodeBuilder();
    
        int hashCode = builder
            .append((Object) null)
            .append((String) null) 
            .append((Object[]) null)
            .append((int[]) null)
            .toHashCode();
    
        assertNotEquals(0, hashCode);
        assertEquals(hashCode, builder.build().intValue());
    }
}