
// Generated by Qodo Gen
package org.apache.commons.lang3.util;
import org.apache.commons.lang3.util.IterableStringTokenizer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.List;

public class IterableStringTokenizerQodoTest {


    // Tokenize string with default delimiters and iterate through tokens
    @Test
    public void test_tokenize_with_default_delimiters() {
        IterableStringTokenizer tokenizer = new IterableStringTokenizer("hello world test");
    
        List<String> tokens = new ArrayList<>();
        for (String token : tokenizer) {
            tokens.add(token);
        }
    
        assertAll(
            () -> assertEquals(3, tokens.size()),
            () -> assertEquals("hello", tokens.get(0)),
            () -> assertEquals("world", tokens.get(1)), 
            () -> assertEquals("test", tokens.get(2))
        );
    }

    // Empty string input should return empty collection/array/stream
    @Test
    public void test_empty_string_returns_empty_collections() {
        IterableStringTokenizer tokenizer = new IterableStringTokenizer("");
    
        assertAll(
            () -> assertEquals(0, tokenizer.toArray().length),
            () -> assertTrue(tokenizer.toList().isEmpty()),
            () -> assertEquals(0, tokenizer.toStream().count())
        );
    }
}