
// Generated by Qodo Gen

import org.apache.commons.lang3.function.Failable;

import org.apache.commons.lang3.function.FailableConsumer;
import org.apache.commons.lang3.function.FailableRunnable;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.io.UncheckedIOException;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class FailableQodoTest {


    // Convert checked exceptions into unchecked RuntimeExceptions when executing failable operations
    @Test
    public void test_checked_exception_converted_to_runtime_exception() {
        FailableRunnable<IOException> throwingRunnable = () -> {
            throw new IOException("test exception");
        };
    
        assertThrows(UncheckedIOException.class, () -> {
            Failable.run(throwingRunnable);
        });
    }

    // Handle null inputs for consumers, suppliers, predicates and functions
    @Test
    public void test_null_consumer_handled_safely() {
        FailableConsumer<String, RuntimeException> nullConsumer = null;
    
        assertDoesNotThrow(() -> {
            Failable.accept(nullConsumer, "test");
        });
    }
}