
// Generated by Qodo Gen

import org.apache.commons.lang3.tuple.MutableTriple;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class MutableTripleQodoTest {


    // Create mutable triple with three non-null values and verify getters return correct values
    @Test
    public void test_mutable_triple_getters_return_correct_values() {
        String left = "left";
        Integer middle = 123;
        Double right = 45.6;
    
        MutableTriple<String, Integer, Double> triple = new MutableTriple<>(left, middle, right);
    
        assertEquals(left, triple.getLeft());
        assertEquals(middle, triple.getMiddle());
        assertEquals(right, triple.getRight());
    }

    // Create mutable triple using ofNonNull() with null values should throw NPE
    @Test
    public void test_of_non_null_with_null_values_throws_npe() {
        assertThrows(NullPointerException.class, () -> {
            MutableTriple.ofNonNull("valid", null, "valid");
        });
    
        assertThrows(NullPointerException.class, () -> {
            MutableTriple.ofNonNull(null, "valid", "valid"); 
        });
    
        assertThrows(NullPointerException.class, () -> {
            MutableTriple.ofNonNull("valid", "valid", null);
        });
    }
}