
// Generated by Qodo Gen

import org.apache.commons.lang3.concurrent.ConcurrentException;
import org.apache.commons.lang3.concurrent.ConcurrentInitializer;
import org.apache.commons.lang3.concurrent.ConcurrentUtils;

import org.junit.jupiter.api.Test;

import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;

public class ConcurrentUtilsQodoTest {


    // ConstantFuture returns provided value immediately without blocking
    @Test
    public void test_constant_future_returns_value_immediately() {
        String testValue = "test";
        Future<String> future = ConcurrentUtils.constantFuture(testValue);

        assertAll(
            () -> assertEquals(testValue, future.get()),
            () -> assertEquals(testValue, future.get(1, TimeUnit.SECONDS)),
            () -> assertTrue(future.isDone()),
            () -> assertFalse(future.isCancelled())
        );
    }

    // Null handling for map parameter in putIfAbsent and createIfAbsent methods
    @Test
    public void test_null_map_handling() throws ConcurrentException {
        ConcurrentMap<String, Integer> nullMap = null;
        ConcurrentInitializer<Integer> initializer = () -> 42;

        assertAll(
            () -> assertNull(ConcurrentUtils.putIfAbsent(nullMap, "key", 1)),
            () -> assertNull(ConcurrentUtils.createIfAbsent(nullMap, "key", initializer))
        );
    }
}