
// Generated by Qodo Gen

import org.apache.commons.lang3.math.NumberUtils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigDecimal;

public class NumberUtilsQodoTest {


    // Compare numeric values of same type (byte, int, long, short) and return correct ordering (-1, 0, 1)
    @Test
    public void test_compare_returns_correct_ordering() {
        assertEquals(-1, NumberUtils.compare((byte)1, (byte)2));
        assertEquals(0, NumberUtils.compare((byte)2, (byte)2));
        assertEquals(1, NumberUtils.compare((byte)3, (byte)2));

        assertEquals(-1, NumberUtils.compare(1, 2));
        assertEquals(0, NumberUtils.compare(2, 2)); 
        assertEquals(1, NumberUtils.compare(3, 2));

        assertEquals(-1, NumberUtils.compare(1L, 2L));
        assertEquals(0, NumberUtils.compare(2L, 2L));
        assertEquals(1, NumberUtils.compare(3L, 2L));

        assertEquals(-1, NumberUtils.compare((short)1, (short)2));
        assertEquals(0, NumberUtils.compare((short)2, (short)2));
        assertEquals(1, NumberUtils.compare((short)3, (short)2));
    }

    // Handle null inputs by returning null or default values
    @Test
    public void test_null_inputs_return_null_or_default() {
        assertNull(NumberUtils.createInteger(null));
        assertEquals(Integer.valueOf(5), NumberUtils.createInteger("5"));

        assertNull(NumberUtils.createLong(null)); 
        assertEquals(Long.valueOf(5), NumberUtils.createLong("5"));

        assertNull(NumberUtils.createDouble(null));
        assertEquals(Double.valueOf(5.5), NumberUtils.createDouble("5.5"));

        assertNull(NumberUtils.createFloat(null));
        assertEquals(Float.valueOf(5.5f), NumberUtils.createFloat("5.5"));

        assertNull(NumberUtils.createBigDecimal(null));
        assertEquals(BigDecimal.valueOf(5.5), NumberUtils.createBigDecimal("5.5"));
    }
}