
// Generated by Qodo Gen

import org.apache.commons.lang3.reflect.ConstructorUtils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.lang.reflect.Constructor;

public class ConstructorUtilsQodoTest {


    // Get accessible constructor with exact parameter types match
    @Test
    public void test_get_accessible_constructor_with_exact_parameter_match() {
        Constructor<String> constructor = ConstructorUtils.getAccessibleConstructor(String.class, char[].class);

        assertNotNull(constructor);
        assertEquals(String.class, constructor.getDeclaringClass());
        assertEquals(1, constructor.getParameterCount());
        assertEquals(char[].class, constructor.getParameterTypes()[0]);
    }

    // Handle null input parameters for constructor invocation
    @Test
    public void test_invoke_constructor_with_null_parameters() throws Exception {
        Object[] args = null;
        Class<?>[] paramTypes = null;

        StringBuilder result = ConstructorUtils.invokeConstructor(StringBuilder.class, args, paramTypes);

        assertNotNull(result);
        assertEquals(0, result.length());
    }
}