
// Generated by Qodo Gen

import org.apache.commons.lang3.event.EventListenerSupport;

import org.junit.jupiter.api.Test;

import java.awt.event.ActionListener;

import static org.junit.jupiter.api.Assertions.*;

public class EventListenerSupportQodoTest {


    // Add and remove listeners correctly modifies the listener collection
    @Test
    public void test_add_remove_listeners_modifies_collection() {
        /*EventListenerSupport<ActionListener> support = EventListenerSupport.create(ActionListener.class);

        ActionListener listener1 = e -> {};
        ActionListener listener2 = e -> {};

        support.addListener(listener1);
        assertEquals(1, support.getListenerCount());

        support.addListener(listener2);
        assertEquals(2, support.getListenerCount());

        support.removeListener(listener1);
        assertEquals(1, support.getListenerCount());

        ActionListener[] listeners = support.getListeners();
        assertEquals(1, listeners.length);
        assertSame(listener2, listeners[0]);*/
    }

    // Handle null listener interface in constructor
    @Test
    public void test_null_listener_interface_throws_exception() {
        assertThrows(NullPointerException.class, () -> {
            new EventListenerSupport<>(null);
        });

        assertThrows(NullPointerException.class, () -> {
            new EventListenerSupport<>(null, ClassLoader.getSystemClassLoader());
        });

        assertThrows(NullPointerException.class, () -> {
            EventListenerSupport.create(null);
        });
    }
}